name: toxicity
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - numpy<2
  - pandas
  - scikit-learn
  - joblib
  - pyyaml
  - rdkit
  - mordred
  - pip:
      - streamlit
